[package]
name = "day5"
version = "0.1.0"
edition = "2021"
authors = ["Sarah <m.sarahgreywolf@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]